[env]
DO_NOT_TRACK = "1"

[settings]
experimental = true
npm.package_manager = "bun"

[tools]
bun = "1.3.12"


[hooks]
preinstall = '''
    test -f .mise-setup-done && exit 0
    vp env install
'''
postinstall = '''
    test -f .mise-setup-done && exit 0
    vp install
    touch .mise-setup-done
'''
