/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GuardRouteRouteImport } from './routes/_guard/route'
import { Route as GuardIndexRouteImport } from './routes/_guard/index'

const GuardRouteRoute = GuardRouteRouteImport.update({
  id: '/_guard',
  getParentRoute: () => rootRouteImport,
} as any)
const GuardIndexRoute = GuardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GuardRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof GuardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof GuardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_guard': typeof GuardRouteRouteWithChildren
  '/_guard/': typeof GuardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/'
  id: '__root__' | '/_guard' | '/_guard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  GuardRouteRoute: typeof GuardRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_guard': {
      id: '/_guard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof GuardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guard/': {
      id: '/_guard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof GuardIndexRouteImport
      parentRoute: typeof GuardRouteRoute
    }
  }
}

interface GuardRouteRouteChildren {
  GuardIndexRoute: typeof GuardIndexRoute
}

const GuardRouteRouteChildren: GuardRouteRouteChildren = {
  GuardIndexRoute: GuardIndexRoute,
}

const GuardRouteRouteWithChildren = GuardRouteRoute._addFileChildren(
  GuardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  GuardRouteRoute: GuardRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
