/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GuardRouteRouteImport } from './routes/_guard/route'
import { Route as GuardIndexRouteImport } from './routes/_guard/index'
import { Route as GuardTanstackQueryServerRouteImport } from './routes/_guard/tanstack-query-server'
import { Route as GuardTanstackQueryRouteImport } from './routes/_guard/tanstack-query'

const GuardRouteRoute = GuardRouteRouteImport.update({
  id: '/_guard',
  getParentRoute: () => rootRouteImport,
} as any)
const GuardIndexRoute = GuardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GuardRouteRoute,
} as any)
const GuardTanstackQueryServerRoute =
  GuardTanstackQueryServerRouteImport.update({
    id: '/tanstack-query-server',
    path: '/tanstack-query-server',
    getParentRoute: () => GuardRouteRoute,
  } as any)
const GuardTanstackQueryRoute = GuardTanstackQueryRouteImport.update({
  id: '/tanstack-query',
  path: '/tanstack-query',
  getParentRoute: () => GuardRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof GuardIndexRoute
  '/tanstack-query': typeof GuardTanstackQueryRoute
  '/tanstack-query-server': typeof GuardTanstackQueryServerRoute
}
export interface FileRoutesByTo {
  '/tanstack-query': typeof GuardTanstackQueryRoute
  '/tanstack-query-server': typeof GuardTanstackQueryServerRoute
  '/': typeof GuardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_guard': typeof GuardRouteRouteWithChildren
  '/_guard/tanstack-query': typeof GuardTanstackQueryRoute
  '/_guard/tanstack-query-server': typeof GuardTanstackQueryServerRoute
  '/_guard/': typeof GuardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/tanstack-query' | '/tanstack-query-server'
  fileRoutesByTo: FileRoutesByTo
  to: '/tanstack-query' | '/tanstack-query-server' | '/'
  id:
    | '__root__'
    | '/_guard'
    | '/_guard/tanstack-query'
    | '/_guard/tanstack-query-server'
    | '/_guard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  GuardRouteRoute: typeof GuardRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_guard': {
      id: '/_guard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof GuardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guard/': {
      id: '/_guard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof GuardIndexRouteImport
      parentRoute: typeof GuardRouteRoute
    }
    '/_guard/tanstack-query-server': {
      id: '/_guard/tanstack-query-server'
      path: '/tanstack-query-server'
      fullPath: '/tanstack-query-server'
      preLoaderRoute: typeof GuardTanstackQueryServerRouteImport
      parentRoute: typeof GuardRouteRoute
    }
    '/_guard/tanstack-query': {
      id: '/_guard/tanstack-query'
      path: '/tanstack-query'
      fullPath: '/tanstack-query'
      preLoaderRoute: typeof GuardTanstackQueryRouteImport
      parentRoute: typeof GuardRouteRoute
    }
  }
}

interface GuardRouteRouteChildren {
  GuardTanstackQueryRoute: typeof GuardTanstackQueryRoute
  GuardTanstackQueryServerRoute: typeof GuardTanstackQueryServerRoute
  GuardIndexRoute: typeof GuardIndexRoute
}

const GuardRouteRouteChildren: GuardRouteRouteChildren = {
  GuardTanstackQueryRoute: GuardTanstackQueryRoute,
  GuardTanstackQueryServerRoute: GuardTanstackQueryServerRoute,
  GuardIndexRoute: GuardIndexRoute,
}

const GuardRouteRouteWithChildren = GuardRouteRoute._addFileChildren(
  GuardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  GuardRouteRoute: GuardRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
